### ISSUE TITLE
WebSocketWriter, its thread and its socket are never cleaned up.

### ISSUE THREAD

**Issue by taylor-b** [crossbario/autobahn-java#107]
The `WebSocketWriter` seems to only call `quit` on its `Looper` when it receives a `WebSocketMessage.Quit` message. But this only occurs in the case of an error. So in the normal case where a socket is connected, used successfully, then disconnected, the socket and its thread are leaked. Along with a few pipes, it appears, probably as part of the `Thread` and/or `Looper` implementation.

This can be a big problem on Android where there are only 1024 file descriptors available, and an app may create many WebSockets in its lifetime.

**Comment by om26er** [comment]
I think you are right, I have been looking around this part of the codebase and have found we are leaking quite a few things. Currently we do not close the TCP connection on a normal onClose, there is other leakage as well, which causes OOM killer on Android to kill the app after a few dozen subsequent connection are created.

Note: This bug is also causing the TestSuiteClientActivity to not produce correct results.

**Comment by om26er** [comment]
This is fixed on master, we can close this.
