### ISSUE TITLE
Include into android project

### ISSUE THREAD

**Issue by i39anisimov** [crossbario/autobahn-java#218]
Hello guys!

Could you help me with including dependency into android project with gradle.

Thanks a lot!

**Comment by om26er** [comment]
First, I wouldn't recommend using autobahn-java in its current state. We are actively working on it, though WAMP support is not there yet.

Regarding adding autobahn-java into android project, that is not possible yet, as we have not published the project to maven/jcenter since we consider it WIP. If you want to build the aar file yourself for use in your Android project, you may clone and build the project and then put the .aar file in your project' libs directory.

**Comment by i39anisimov** [comment]
@om26er Oh, thanks for answer.

Good luck in your work!
