### ISSUE TITLE
Document different authentication methods

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#360]
There are two parts
* add examples to README.md
* Add real, working Java code

**Comment by om26er** [comment]
The example code for authentications already exists here https://github.com/crossbario/autobahn-java/blob/master/demo-gallery/src/main/java/io/crossbar/autobahn/demogallery/AuthenticationExampleClient.java

Need to fill up the README.

**Comment by oberstet** [comment]
actually, this would be a good chance to add CI tests too! as in, expand https://github.com/crossbario/autobahn-java/blob/master/.travis.yml, so that it runs not only 1 program, but eg 3 more for the 3 auth methods currently available, and then have the CB tested against have preconfigured static auth credentials in the CB node config.

**Comment by om26er** [comment]
README.md updated https://github.com/crossbario/autobahn-java/pull/371

**Comment by om26er** [comment]
this landed.
