### ISSUE TITLE
Dynamically allow to change Transport' auto ping interval

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#388]
Currently we provide TransportOptions when connecting to a crossbar instance, we need to be able to do that dynamically so that when, for example an app goes to background on an Android device, its able to adjust ping/pong frequency as required.

All that, without reconnecting.

**Comment by oberstet** [comment]
How about this? in the implementation of `TransportOptions.setAutoPingInterval`, we:

* check if the object has a transport attached (needs a new private member, and transport setter)
* if so, stop the current auto pinger and start a new one with the given new interval
* set the new interval on the private member

_if_ the stopping and starting of a currently running auto-pinger runs async, then the `TransportOptions.setAutoPingInterval` method would probably need to return a future also. not sure if that is the case.

when an instance of `TransportOptions` is passed into the constructor of a transport, the transport can then attach itself to the options so that it can be called when an option changes.

alternatively, maybe even better: make TransportOptions into an Observable, like with "onOptionChanged". However, decoupling the actual execution of the option change from the return to the client code initiating the change makes it impossible to deny a change or error back.

yet another solution:

* we add a `Transport.setOptions()` method to transports, and allow setting this even while a transport is running - as long as the specific option can be changed while the transport is running
* any option with a value unchanged from the inital one is ignored, a changed option then triggers code that issues appropriate actions (which might include stopping a running auto-pinger, and restarting with new values etc)

**Comment by om26er** [comment]
landed via https://github.com/crossbario/autobahn-java/pull/394
