### ISSUE TITLE
Build version and documentation need updating

### ISSUE THREAD

**Issue by jellisgwn** [crossbario/autobahn-java#415]
1. When building library from source the command is:
```
make build_netty
```
and not:
```
$ make build_autobahn
make: *** No rule to make target `build_autobahn'.  Stop.
```

2. The `autobahn/README.md` references `mvn clean install` but the project does not include a pom.

3. The  version in the `autobahn/build.gradle` is 18.3.1:
```
def relVersion = System.getenv().containsKey('AUTOBAHN_BUILD_VERSION') ? System.getenv(
        'AUTOBAHN_BUILD_VERSION'): '18.3.1'
```
and should be bumped to 18.5.2.

**Comment by om26er** [comment]
> The version in the autobahn/build.gradle is 18.3.1:

this does not need an update, as part of the release process we export AUTOBAHN_BUILD_VERSION into the environment and the version is picked from there.

**Comment by jellisgwn** [comment]
i'm not building with your release process... which means this either needs to be kept in sync (as the autobahn/README.md suggests) or the build process needs to be updated to include setting this variable in the environment.

**Comment by om26er** [comment]
@jellisgwn This PR https://github.com/crossbario/autobahn-java/pull/416 removes those references because they are from the time when we were not using gradle, sorry for the confusion that might have caused.

Currently, we do bump the release version in `Makefile` on the root of the source, there the variable is AUTOBAHN_JAVA_VERSION.

To build for Android, you have to build using Android Studio. For non-Android systems i.e. Netty, you can use `make build_netty` on the root of the project. Note that requires `make` and `docker` on your system.

I think there is plenty of room there for improvement of documentation there, I will work to improve that.

**Comment by jellisgwn** [comment]
Yep, i'm building for non-Android, and have navigated the make / docker build. It was just surprising to get to the end of the build and see:
```
$ ls autobahn/build/libs/
autobahn-18.3.1.jar
```
the `build_netty` target does not seem to care about the `AUTOBAHN_JAVA_VERSION` variable
```
build_netty:
        docker run -it --rm \
                -v ${shell pwd}:/workspace \
                crossbario/autobahn-java:netty \
                gradle -PbuildPlatform=netty distZip
```
and therefore picks it up from the `build.gradle`.

**Comment by om26er** [comment]
OK, I have a fix for that here https://github.com/crossbario/autobahn-java/pull/416/commits/eac6fb44356b25ea86d2c12247b7d0ade35733a3

**Comment by jellisgwn** [comment]
@om26er will you be creating a new release to pick up recent changes? i expect to be picking up on autobahn-java shortly and would like to pick up the changes made during the summer in a new release.

**Comment by oberstet** [comment]
release v19.3.1 is published
