### ISSUE TITLE
NettyWebSocket transport should not offer compression

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#503]
NettyWebSocket offers WebSocket compression, this seems to break our WAMP implementation. After the successful WebSocket handshake, no WAMP messages are delivered to the router.

This puts app code to state where it is stuck forever. The WebSocket ping/pong keeps working hence onDisconnect on the WAMP session side never gets called. Netty doesn't produce any errors at all.

This issue was spotted while trying to debug https://forum.crossbar.io/t/can-connect-but-not-join-to-crossbar-plain-java/1838

**Comment by oberstet** [comment]
interesting. agree: for now, I think it's good enough to just deactivate compression. in general, I'd be curious what's the root cause / issue here (but I am confident the issue is more likely on nettys side - ABPy/CB is exhaustively tested for WS compression, and used with such eg from ABJS/browsers)
